# ===========================
# Repository Labels Definition
# ===========================
# 저장소의 라벨을 정의합니다.
# 이 파일을 사용하여 라벨을 동기화하려면 labels.yml 워크플로우를 사용하세요.
#
# 사용법:
#   gh label import labels.yml  (GitHub CLI)
#   또는 .github/workflows/labels.yml 워크플로우 사용

# ===================
# Type Labels (유형)
# ===================
- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: enhancement
  color: "a2eeef"
  description: "New feature or request"

- name: documentation
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: question
  color: "d876e3"
  description: "Further information is requested"

- name: refactor
  color: "fbca04"
  description: "Code improvement without adding features"

- name: test
  color: "bfd4f2"
  description: "Adding or updating tests"

- name: chore
  color: "fef2c0"
  description: "Maintenance tasks"

# ===================
# Priority Labels (우선순위)
# ===================
- name: "priority: critical"
  color: "b60205"
  description: "Must be fixed ASAP"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

# ===================
# Status Labels (상태)
# ===================
- name: triage
  color: "ededed"
  description: "Needs triage"

- name: "status: in progress"
  color: "0052cc"
  description: "Currently being worked on"

- name: "status: blocked"
  color: "b60205"
  description: "Blocked by another issue"

- name: "status: needs review"
  color: "fbca04"
  description: "Needs review"

- name: "status: approved"
  color: "0e8a16"
  description: "Approved and ready to merge"

- name: "status: on hold"
  color: "c5def5"
  description: "On hold"

# ===================
# Area Labels (영역)
# ===================
- name: "area: ai-agent"
  color: "7057ff"
  description: "AI Agent configuration"

- name: "area: ci-cd"
  color: "006b75"
  description: "CI/CD pipelines"

- name: "area: security"
  color: "d73a4a"
  description: "Security related"

- name: "area: api"
  color: "1d76db"
  description: "API related"

- name: "area: frontend"
  color: "c5def5"
  description: "Frontend related"

- name: "area: backend"
  color: "bfdadc"
  description: "Backend related"

- name: "area: database"
  color: "f9d0c4"
  description: "Database related"

- name: "area: infrastructure"
  color: "d4c5f9"
  description: "Infrastructure related"

# ===================
# Technology Labels (기술)
# ===================
- name: typescript
  color: "3178c6"
  description: "TypeScript related"

- name: python
  color: "3776ab"
  description: "Python related"

- name: github-actions
  color: "2088ff"
  description: "GitHub Actions"

- name: docker
  color: "2496ed"
  description: "Docker related"

# ===================
# Special Labels (특수)
# ===================
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: dependencies
  color: "0366d6"
  description: "Dependency updates"

- name: duplicate
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: invalid
  color: "e4e669"
  description: "This doesn't seem right"

- name: wontfix
  color: "ffffff"
  description: "This will not be worked on"

- name: stale
  color: "ededed"
  description: "No recent activity"

# ===================
# Operations Labels (운영)
# ===================
- name: incident
  color: "b60205"
  description: "Production incident"

- name: rollback
  color: "d93f0b"
  description: "Deployment rollback"

- name: staging
  color: "fbca04"
  description: "Staging environment"

- name: production
  color: "b60205"
  description: "Production environment"

- name: pinned
  color: "006b75"
  description: "Pinned issue - exempt from stale"

- name: sync-needed
  color: "d93f0b"
  description: "Documentation sync needed"

- name: code-analysis
  color: "1d76db"
  description: "Code analysis report"

- name: ai-generated
  color: "9b59b6"
  description: "Generated by AI"

# ===================
# AI Related (AI 관련)
# ===================
- name: "ai: assisted"
  color: "9b59b6"
  description: "Created with AI assistance"

- name: "ai: review needed"
  color: "e74c3c"
  description: "AI-generated code needs human review"

- name: "ai: prompt"
  color: "3498db"
  description: "Related to AI prompts"

# ===================
# Size Labels (크기)
# ===================
- name: "size: XS"
  color: "3CBF00"
  description: "Extra small change (< 10 lines)"

- name: "size: S"
  color: "5D9801"
  description: "Small change (10-50 lines)"

- name: "size: M"
  color: "7F7203"
  description: "Medium change (50-200 lines)"

- name: "size: L"
  color: "A14C05"
  description: "Large change (200-500 lines)"

- name: "size: XL"
  color: "C32607"
  description: "Extra large change (> 500 lines)"
